spring:
    profiles:
        active: dev

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shit_blog
      username: root
      password: 123

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: true

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

